language: python
python:
  - "3.13"

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate

script:
  - black --check .
  - flake8
  - coverage run --source=polls manage.py test
  - coverage report

after_success:
  - export COVERALLS_BRANCH=$TRAVIS_BRANCH
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: us-east-2
  app: djangoPA1-v2
  env: djangoPA1-env
  bucket_name: elasticbeanstalk-us-east-2-127471246260
  bucket_path: djangoPA1-v2
  on:
    branch: main
  skip_cleanup: true

notifications:
  email:
    on_success: change
    on_failure: always

